### ISSUE TITLE
Use `Guard::Plugin` instead of `Guard::Guard`

### ISSUE THREAD

**Issue by hauleth** [alexgb/guard-konacha#28]
```
    ******** BIG DEPRECATION WARNING !! ********

    Hi, Guard here.

    You're including lib/guard/guard.rb ...

    ... which contains code deprecated over a year ago!


    This file will likely be removed in the next version, so make sure you're
    not requiring it anywhere to ensure safe gem upgrades.

    If this message is annoying and you can't quickly fix the issue (see below),
    you have 2 options:

      1) Simply set the env variable "GUARD_GEM_SILENCE_DEPRECATIONS" to "1" to
      skip this message

      2) Freeze the gem to a previous version (not recommended because upgrades
      are cool and you might forget to unfreeze later!).

      E.g. in your Gemfile:

        if Time.now > Time.new(2014,11,10)
          gem 'guard', '~> 2.8'
        else
          # Freeze until 2014-11-10 - in case we forget to change back ;)
          gem 'guard', '= 2.7.3'
        end

    If you don't know which gem or plugin is requiring this file, here's a
    backtrace:

    /home/hauleth/Workspace/orodruin/vendor/bundle/ruby/2.1.0/gems/guard-2.8.2/lib/guard/guard.rb:45:in `<module:Guard>'
         >> /home/hauleth/Workspace/orodruin/vendor/bundle/ruby/2.1.0/gems/guard-2.8.2/lib/guard/guard.rb:3:in `<top (required)>'
         >> /home/hauleth/Workspace/orodruin/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:252:in `require'
         >> /home/hauleth/Workspace/orodruin/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:252:in `block in require'
         >> /home/hauleth/Workspace/orodruin/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:237:in `load_dependency'"

    Here's how to quickly upgrade/fix this (given you are a maintainer of the
    offending plugin or you want to prepare a pull request yourself):

      https://github.com/guard/guard/wiki/Upgrading-to-Guard-2.0#changes-in-guardguard

    Have fun!

    ******** END OF DEPRECATION MESSAGE ********
```

**Comment by tapickell** [comment]
Seeing the same here, we have removed this from our gemfile until this is resolved.

**Comment by pjmorse** [comment]
Stuck on this one here, too, over a year later. Is this going to be addressed?
